"""add is_active to enrollments

Revision ID: 3e2f42db15f4
Revises: 6e5118330a57
Create Date: 2026-02-07 13:33:41.194317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2f42db15f4'
down_revision: Union[str, Sequence[str], None] = '6e5118330a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column as nullable first OR provide a server_default
#op.add_column('enrollments', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'is_active')
    # ### end Alembic commands ###
